FROM tensorflow/tensorflow:1.13.1-py3

#ADD PACKAGES
RUN pip install \
	gunicorn \
	flask \
	Pillow

#ADD CODE
ADD ./app /opt/webapp/
WORKDIR /opt/webapp

#RESET ENTRYPOINT
ENTRYPOINT []

CMD gunicorn --bind 0.0.0.0:8888 wsgi

